/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 10.3.0-1ubuntu1~20.10 -fPIC -Os) */

(* top =  1  *)
(* src = "pixelSensorFsm.v:32" *)
module pixelSensorFsm(clk, reset, erase, expose, readStateOn, read0, read1, read2, read3, convert);
  (* src = "pixelSensorFsm.v:142" *)
  wire [31:0] _000_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _001_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _002_;
  (* src = "pixelSensorFsm.v:142" *)
  wire [2:0] _003_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _004_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _005_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _006_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _007_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _008_;
  (* src = "pixelSensorFsm.v:142" *)
  wire [2:0] _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _247_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _248_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _249_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _250_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _251_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _252_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _253_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _254_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _255_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _256_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _257_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _258_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _259_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _260_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _261_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _262_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _263_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _264_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _265_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _266_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _267_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _268_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _269_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _270_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _271_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _272_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _273_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _274_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _275_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _276_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _277_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _278_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _279_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _280_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _281_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _282_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _283_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _284_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _285_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _286_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _287_;
  (* src = "pixelSensorFsm.v:67" *)
  wire _288_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _289_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _290_;
  (* src = "pixelSensorFsm.v:142" *)
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _308_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _309_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _310_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _311_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _312_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _313_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _314_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _315_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _316_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _317_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _318_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _319_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _320_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _321_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _322_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _323_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _324_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _325_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _326_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _327_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _328_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _329_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _330_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _331_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _332_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _333_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _334_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _335_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _336_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _337_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _338_;
  (* src = "pixelSensorFsm.v:63" *)
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _440_;
  wire _441_;
  wire _442_;
  wire _443_;
  wire _444_;
  wire _445_;
  wire _446_;
  wire _447_;
  wire _448_;
  wire _449_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  wire _466_;
  wire _467_;
  wire _468_;
  wire _469_;
  wire _470_;
  wire _471_;
  wire _472_;
  wire _473_;
  wire _474_;
  wire _475_;
  wire _476_;
  wire _477_;
  wire _478_;
  wire _479_;
  wire _480_;
  wire _481_;
  wire _482_;
  wire _483_;
  wire _484_;
  wire _485_;
  wire _486_;
  wire _487_;
  wire _488_;
  wire _489_;
  wire _490_;
  wire _491_;
  wire _492_;
  wire _493_;
  wire _494_;
  wire _495_;
  wire _496_;
  wire _497_;
  wire _498_;
  wire _499_;
  wire _500_;
  wire _501_;
  wire _502_;
  wire _503_;
  wire _504_;
  wire _505_;
  wire _506_;
  wire _507_;
  wire _508_;
  wire _509_;
  wire _510_;
  wire _511_;
  wire _512_;
  wire _513_;
  wire _514_;
  wire _515_;
  wire _516_;
  wire _517_;
  wire _518_;
  wire _519_;
  wire _520_;
  wire _521_;
  wire _522_;
  wire _523_;
  wire _524_;
  wire _525_;
  wire _526_;
  wire _527_;
  wire _528_;
  wire _529_;
  wire _530_;
  wire _531_;
  wire _532_;
  wire _533_;
  wire _534_;
  wire _535_;
  wire _536_;
  wire _537_;
  wire _538_;
  wire _539_;
  wire _540_;
  wire _541_;
  wire _542_;
  wire _543_;
  wire _544_;
  wire _545_;
  wire _546_;
  wire _547_;
  wire _548_;
  wire _549_;
  wire _550_;
  wire _551_;
  wire _552_;
  wire _553_;
  wire _554_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _555_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _556_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _557_;
  wire _558_;
  wire _559_;
  wire _560_;
  wire _561_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _562_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _563_;
  (* src = "pixelSensorFsm.v:61" *)
  wire _564_;
  wire _565_;
  wire _566_;
  wire _567_;
  wire _568_;
  wire _569_;
  wire _570_;
  wire _571_;
  wire _572_;
  wire _573_;
  wire _574_;
  wire _575_;
  wire _576_;
  wire _577_;
  wire _578_;
  wire _579_;
  wire _580_;
  wire _581_;
  wire _582_;
  wire _583_;
  wire _584_;
  wire _585_;
  wire _586_;
  wire _587_;
  wire _588_;
  wire _589_;
  wire _590_;
  wire _591_;
  wire _592_;
  wire _593_;
  wire _594_;
  wire _595_;
  wire _596_;
  wire _597_;
  wire _598_;
  wire _599_;
  wire _600_;
  wire _601_;
  wire _602_;
  wire _603_;
  wire _604_;
  wire _605_;
  wire _606_;
  wire _607_;
  wire _608_;
  wire _609_;
  wire _610_;
  wire _611_;
  wire _612_;
  wire _613_;
  wire _614_;
  wire _615_;
  wire _616_;
  (* src = "pixelSensorFsm.v:33" *)
  input clk;
  (* src = "pixelSensorFsm.v:42" *)
  output convert;
  (* src = "pixelSensorFsm.v:63" *)
  wire [31:0] counter;
  (* src = "pixelSensorFsm.v:35" *)
  output erase;
  (* src = "pixelSensorFsm.v:36" *)
  output expose;
  (* src = "pixelSensorFsm.v:61" *)
  wire [2:0] next_state;
  (* src = "pixelSensorFsm.v:38" *)
  output read0;
  (* src = "pixelSensorFsm.v:39" *)
  output read1;
  (* src = "pixelSensorFsm.v:40" *)
  output read2;
  (* src = "pixelSensorFsm.v:41" *)
  output read3;
  (* onehot = 32'd1 *)
  wire [3:0] readState;
  (* src = "pixelSensorFsm.v:37" *)
  output readStateOn;
  (* src = "pixelSensorFsm.v:34" *)
  input reset;
  (* src = "pixelSensorFsm.v:61" *)
  wire [2:0] state;
  IVX1_CV _617_ (
    .A(_308_),
    .Y(_340_)
  );
  IVX1_CV _618_ (
    .A(_333_),
    .Y(_341_)
  );
  IVX1_CV _619_ (
    .A(_335_),
    .Y(_342_)
  );
  IVX1_CV _620_ (
    .A(_564_),
    .Y(_343_)
  );
  ANX1_CV _621_ (
    .A(_563_),
    .B(_562_),
    .Y(_344_)
  );
  NDX1_CV _622_ (
    .A(_304_),
    .B(_344_),
    .Y(_345_)
  );
  IVX1_CV _623_ (
    .A(_345_),
    .Y(_288_)
  );
  NRX1_CV _624_ (
    .A(_312_),
    .B(_311_),
    .Y(_346_)
  );
  NRX1_CV _625_ (
    .A(_314_),
    .B(_313_),
    .Y(_347_)
  );
  ANX1_CV _626_ (
    .A(_346_),
    .B(_347_),
    .Y(_348_)
  );
  NRX1_CV _627_ (
    .A(_339_),
    .B(_338_),
    .Y(_349_)
  );
  NRX1_CV _628_ (
    .A(_310_),
    .B(_309_),
    .Y(_350_)
  );
  ANX1_CV _629_ (
    .A(_349_),
    .B(_350_),
    .Y(_351_)
  );
  ANX1_CV _630_ (
    .A(_348_),
    .B(_351_),
    .Y(_352_)
  );
  NRX1_CV _631_ (
    .A(_321_),
    .B(_320_),
    .Y(_353_)
  );
  NRX1_CV _632_ (
    .A(_323_),
    .B(_322_),
    .Y(_354_)
  );
  ANX1_CV _633_ (
    .A(_353_),
    .B(_354_),
    .Y(_355_)
  );
  NRX1_CV _634_ (
    .A(_316_),
    .B(_315_),
    .Y(_356_)
  );
  NRX1_CV _635_ (
    .A(_318_),
    .B(_317_),
    .Y(_357_)
  );
  ANX1_CV _636_ (
    .A(_356_),
    .B(_357_),
    .Y(_358_)
  );
  ANX1_CV _637_ (
    .A(_355_),
    .B(_358_),
    .Y(_359_)
  );
  NRX1_CV _638_ (
    .A(_329_),
    .B(_328_),
    .Y(_360_)
  );
  NRX1_CV _639_ (
    .A(_332_),
    .B(_331_),
    .Y(_361_)
  );
  ANX1_CV _640_ (
    .A(_360_),
    .B(_361_),
    .Y(_362_)
  );
  NRX1_CV _641_ (
    .A(_325_),
    .B(_324_),
    .Y(_363_)
  );
  NRX1_CV _642_ (
    .A(_327_),
    .B(_326_),
    .Y(_364_)
  );
  ANX1_CV _643_ (
    .A(_363_),
    .B(_364_),
    .Y(_365_)
  );
  ANX1_CV _644_ (
    .A(_362_),
    .B(_365_),
    .Y(_366_)
  );
  ANX1_CV _645_ (
    .A(_359_),
    .B(_366_),
    .Y(_367_)
  );
  ANX1_CV _646_ (
    .A(_352_),
    .B(_367_),
    .Y(_368_)
  );
  NRX1_CV _647_ (
    .A(_337_),
    .B(_336_),
    .Y(_369_)
  );
  NRX1_CV _648_ (
    .A(_334_),
    .B(_335_),
    .Y(_370_)
  );
  ANX1_CV _649_ (
    .A(_369_),
    .B(_370_),
    .Y(_371_)
  );
  ANX1_CV _650_ (
    .A(_368_),
    .B(_371_),
    .Y(_372_)
  );
  NDX1_CV _651_ (
    .A(_330_),
    .B(_341_),
    .Y(_373_)
  );
  NRX1_CV _652_ (
    .A(_319_),
    .B(_373_),
    .Y(_374_)
  );
  ANX1_CV _653_ (
    .A(_308_),
    .B(_374_),
    .Y(_375_)
  );
  NDX1_CV _654_ (
    .A(_372_),
    .B(_375_),
    .Y(_376_)
  );
  ORX1_CV _655_ (
    .A(_345_),
    .B(_376_),
    .Y(_377_)
  );
  NDX1_CV _656_ (
    .A(_563_),
    .B(_304_),
    .Y(_378_)
  );
  ORX1_CV _657_ (
    .A(_562_),
    .B(_378_),
    .Y(_379_)
  );
  ANX1_CV _658_ (
    .A(_308_),
    .B(_319_),
    .Y(_380_)
  );
  ANX1_CV _659_ (
    .A(_330_),
    .B(_380_),
    .Y(_381_)
  );
  ANX1_CV _660_ (
    .A(_333_),
    .B(_381_),
    .Y(_382_)
  );
  ANX1_CV _661_ (
    .A(_334_),
    .B(_382_),
    .Y(_383_)
  );
  ANX1_CV _662_ (
    .A(_335_),
    .B(_383_),
    .Y(_384_)
  );
  ANX1_CV _663_ (
    .A(_336_),
    .B(_384_),
    .Y(_385_)
  );
  ANX1_CV _664_ (
    .A(_337_),
    .B(_385_),
    .Y(_386_)
  );
  NDX1_CV _665_ (
    .A(_368_),
    .B(_386_),
    .Y(_387_)
  );
  ORX1_CV _666_ (
    .A(_379_),
    .B(_387_),
    .Y(_388_)
  );
  NDX1_CV _667_ (
    .A(_345_),
    .B(_388_),
    .Y(_389_)
  );
  NRX1_CV _668_ (
    .A(_308_),
    .B(_330_),
    .Y(_390_)
  );
  ANX1_CV _669_ (
    .A(_319_),
    .B(_390_),
    .Y(_391_)
  );
  ANX1_CV _670_ (
    .A(_333_),
    .B(_391_),
    .Y(_392_)
  );
  NDX1_CV _671_ (
    .A(_372_),
    .B(_392_),
    .Y(_393_)
  );
  ANX1_CV _672_ (
    .A(_376_),
    .B(_393_),
    .Y(_394_)
  );
  NDX1_CV _673_ (
    .A(_304_),
    .B(_376_),
    .Y(_395_)
  );
  ANX1_CV _674_ (
    .A(_288_),
    .B(_394_),
    .Y(_396_)
  );
  NDX1_CV _675_ (
    .A(_288_),
    .B(_394_),
    .Y(_397_)
  );
  ANX1_CV _676_ (
    .A(_389_),
    .B(_397_),
    .Y(_398_)
  );
  ANX1_CV _677_ (
    .A(_372_),
    .B(_382_),
    .Y(_399_)
  );
  ORX1_CV _678_ (
    .A(_397_),
    .B(_399_),
    .Y(_400_)
  );
  ANX1_CV _679_ (
    .A(_389_),
    .B(_400_),
    .Y(_401_)
  );
  ORX1_CV _680_ (
    .A(_300_),
    .B(_401_),
    .Y(_402_)
  );
  NDX1_CV _681_ (
    .A(_377_),
    .B(_402_),
    .Y(_294_)
  );
  ORX1_CV _682_ (
    .A(_345_),
    .B(_393_),
    .Y(_403_)
  );
  ORX1_CV _683_ (
    .A(_299_),
    .B(_401_),
    .Y(_404_)
  );
  NDX1_CV _684_ (
    .A(_403_),
    .B(_404_),
    .Y(_293_)
  );
  NDX1_CV _685_ (
    .A(_562_),
    .B(_304_),
    .Y(_405_)
  );
  ORX1_CV _686_ (
    .A(_563_),
    .B(_405_),
    .Y(_406_)
  );
  IVX1_CV _687_ (
    .A(_406_),
    .Y(_280_)
  );
  ANX1_CV _688_ (
    .A(_288_),
    .B(_399_),
    .Y(_407_)
  );
  NRX1_CV _689_ (
    .A(_298_),
    .B(_407_),
    .Y(_408_)
  );
  ORX1_CV _690_ (
    .A(_345_),
    .B(_394_),
    .Y(_409_)
  );
  NDX1_CV _691_ (
    .A(_408_),
    .B(_409_),
    .Y(_410_)
  );
  NDX1_CV _692_ (
    .A(_388_),
    .B(_410_),
    .Y(_292_)
  );
  NRX1_CV _693_ (
    .A(_301_),
    .B(_398_),
    .Y(_411_)
  );
  ORX1_CV _694_ (
    .A(_407_),
    .B(_411_),
    .Y(_295_)
  );
  NRX1_CV _695_ (
    .A(_563_),
    .B(_562_),
    .Y(_412_)
  );
  ORX1_CV _696_ (
    .A(_563_),
    .B(_562_),
    .Y(_413_)
  );
  NDX1_CV _697_ (
    .A(_564_),
    .B(_412_),
    .Y(_414_)
  );
  ANX1_CV _698_ (
    .A(_340_),
    .B(_414_),
    .Y(_247_)
  );
  NRX1_CV _699_ (
    .A(_308_),
    .B(_319_),
    .Y(_415_)
  );
  EOX1_CV _700_ (
    .A(_308_),
    .B(_319_),
    .Y(_416_)
  );
  ANX1_CV _701_ (
    .A(_414_),
    .B(_416_),
    .Y(_258_)
  );
  EOX1_CV _702_ (
    .A(_330_),
    .B(_380_),
    .Y(_417_)
  );
  ANX1_CV _703_ (
    .A(_414_),
    .B(_417_),
    .Y(_269_)
  );
  ENX1_CV _704_ (
    .A(_341_),
    .B(_381_),
    .Y(_418_)
  );
  ANX1_CV _705_ (
    .A(_414_),
    .B(_418_),
    .Y(_272_)
  );
  EOX1_CV _706_ (
    .A(_334_),
    .B(_382_),
    .Y(_419_)
  );
  ANX1_CV _707_ (
    .A(_414_),
    .B(_419_),
    .Y(_273_)
  );
  ENX1_CV _708_ (
    .A(_342_),
    .B(_383_),
    .Y(_420_)
  );
  ANX1_CV _709_ (
    .A(_414_),
    .B(_420_),
    .Y(_274_)
  );
  EOX1_CV _710_ (
    .A(_336_),
    .B(_384_),
    .Y(_421_)
  );
  ANX1_CV _711_ (
    .A(_414_),
    .B(_421_),
    .Y(_275_)
  );
  EOX1_CV _712_ (
    .A(_337_),
    .B(_385_),
    .Y(_422_)
  );
  ANX1_CV _713_ (
    .A(_414_),
    .B(_422_),
    .Y(_276_)
  );
  ANX1_CV _714_ (
    .A(_338_),
    .B(_386_),
    .Y(_423_)
  );
  ORX1_CV _715_ (
    .A(_338_),
    .B(_386_),
    .Y(_424_)
  );
  NDX1_CV _716_ (
    .A(_414_),
    .B(_424_),
    .Y(_425_)
  );
  NRX1_CV _717_ (
    .A(_423_),
    .B(_425_),
    .Y(_277_)
  );
  ANX1_CV _718_ (
    .A(_339_),
    .B(_423_),
    .Y(_426_)
  );
  ORX1_CV _719_ (
    .A(_339_),
    .B(_423_),
    .Y(_427_)
  );
  NDX1_CV _720_ (
    .A(_414_),
    .B(_427_),
    .Y(_428_)
  );
  NRX1_CV _721_ (
    .A(_426_),
    .B(_428_),
    .Y(_278_)
  );
  ANX1_CV _722_ (
    .A(_309_),
    .B(_426_),
    .Y(_429_)
  );
  ORX1_CV _723_ (
    .A(_309_),
    .B(_426_),
    .Y(_430_)
  );
  NDX1_CV _724_ (
    .A(_414_),
    .B(_430_),
    .Y(_431_)
  );
  NRX1_CV _725_ (
    .A(_429_),
    .B(_431_),
    .Y(_248_)
  );
  ANX1_CV _726_ (
    .A(_310_),
    .B(_429_),
    .Y(_432_)
  );
  ORX1_CV _727_ (
    .A(_310_),
    .B(_429_),
    .Y(_433_)
  );
  NDX1_CV _728_ (
    .A(_414_),
    .B(_433_),
    .Y(_434_)
  );
  NRX1_CV _729_ (
    .A(_432_),
    .B(_434_),
    .Y(_249_)
  );
  ANX1_CV _730_ (
    .A(_311_),
    .B(_432_),
    .Y(_435_)
  );
  ORX1_CV _731_ (
    .A(_311_),
    .B(_432_),
    .Y(_436_)
  );
  NDX1_CV _732_ (
    .A(_414_),
    .B(_436_),
    .Y(_437_)
  );
  NRX1_CV _733_ (
    .A(_435_),
    .B(_437_),
    .Y(_250_)
  );
  ANX1_CV _734_ (
    .A(_312_),
    .B(_435_),
    .Y(_438_)
  );
  ORX1_CV _735_ (
    .A(_312_),
    .B(_435_),
    .Y(_439_)
  );
  NDX1_CV _736_ (
    .A(_414_),
    .B(_439_),
    .Y(_440_)
  );
  NRX1_CV _737_ (
    .A(_438_),
    .B(_440_),
    .Y(_251_)
  );
  ANX1_CV _738_ (
    .A(_313_),
    .B(_438_),
    .Y(_441_)
  );
  ORX1_CV _739_ (
    .A(_313_),
    .B(_438_),
    .Y(_442_)
  );
  NDX1_CV _740_ (
    .A(_414_),
    .B(_442_),
    .Y(_443_)
  );
  NRX1_CV _741_ (
    .A(_441_),
    .B(_443_),
    .Y(_252_)
  );
  ANX1_CV _742_ (
    .A(_314_),
    .B(_441_),
    .Y(_444_)
  );
  ORX1_CV _743_ (
    .A(_314_),
    .B(_441_),
    .Y(_445_)
  );
  NDX1_CV _744_ (
    .A(_414_),
    .B(_445_),
    .Y(_446_)
  );
  NRX1_CV _745_ (
    .A(_444_),
    .B(_446_),
    .Y(_253_)
  );
  ANX1_CV _746_ (
    .A(_315_),
    .B(_444_),
    .Y(_447_)
  );
  ORX1_CV _747_ (
    .A(_315_),
    .B(_444_),
    .Y(_448_)
  );
  NDX1_CV _748_ (
    .A(_414_),
    .B(_448_),
    .Y(_449_)
  );
  NRX1_CV _749_ (
    .A(_447_),
    .B(_449_),
    .Y(_254_)
  );
  ANX1_CV _750_ (
    .A(_316_),
    .B(_447_),
    .Y(_450_)
  );
  ORX1_CV _751_ (
    .A(_316_),
    .B(_447_),
    .Y(_451_)
  );
  NDX1_CV _752_ (
    .A(_414_),
    .B(_451_),
    .Y(_452_)
  );
  NRX1_CV _753_ (
    .A(_450_),
    .B(_452_),
    .Y(_255_)
  );
  ANX1_CV _754_ (
    .A(_317_),
    .B(_450_),
    .Y(_453_)
  );
  ORX1_CV _755_ (
    .A(_317_),
    .B(_450_),
    .Y(_454_)
  );
  NDX1_CV _756_ (
    .A(_414_),
    .B(_454_),
    .Y(_455_)
  );
  NRX1_CV _757_ (
    .A(_453_),
    .B(_455_),
    .Y(_256_)
  );
  ANX1_CV _758_ (
    .A(_318_),
    .B(_453_),
    .Y(_456_)
  );
  ORX1_CV _759_ (
    .A(_318_),
    .B(_453_),
    .Y(_457_)
  );
  NDX1_CV _760_ (
    .A(_414_),
    .B(_457_),
    .Y(_458_)
  );
  NRX1_CV _761_ (
    .A(_456_),
    .B(_458_),
    .Y(_257_)
  );
  ANX1_CV _762_ (
    .A(_320_),
    .B(_456_),
    .Y(_459_)
  );
  ORX1_CV _763_ (
    .A(_320_),
    .B(_456_),
    .Y(_460_)
  );
  NDX1_CV _764_ (
    .A(_414_),
    .B(_460_),
    .Y(_461_)
  );
  NRX1_CV _765_ (
    .A(_459_),
    .B(_461_),
    .Y(_259_)
  );
  ANX1_CV _766_ (
    .A(_321_),
    .B(_459_),
    .Y(_462_)
  );
  ORX1_CV _767_ (
    .A(_321_),
    .B(_459_),
    .Y(_463_)
  );
  NDX1_CV _768_ (
    .A(_414_),
    .B(_463_),
    .Y(_464_)
  );
  NRX1_CV _769_ (
    .A(_462_),
    .B(_464_),
    .Y(_260_)
  );
  ANX1_CV _770_ (
    .A(_322_),
    .B(_462_),
    .Y(_465_)
  );
  ORX1_CV _771_ (
    .A(_322_),
    .B(_462_),
    .Y(_466_)
  );
  NDX1_CV _772_ (
    .A(_414_),
    .B(_466_),
    .Y(_467_)
  );
  NRX1_CV _773_ (
    .A(_465_),
    .B(_467_),
    .Y(_261_)
  );
  ANX1_CV _774_ (
    .A(_323_),
    .B(_465_),
    .Y(_468_)
  );
  ORX1_CV _775_ (
    .A(_323_),
    .B(_465_),
    .Y(_469_)
  );
  NDX1_CV _776_ (
    .A(_414_),
    .B(_469_),
    .Y(_470_)
  );
  NRX1_CV _777_ (
    .A(_468_),
    .B(_470_),
    .Y(_262_)
  );
  ANX1_CV _778_ (
    .A(_324_),
    .B(_468_),
    .Y(_471_)
  );
  ORX1_CV _779_ (
    .A(_324_),
    .B(_468_),
    .Y(_472_)
  );
  NDX1_CV _780_ (
    .A(_414_),
    .B(_472_),
    .Y(_473_)
  );
  NRX1_CV _781_ (
    .A(_471_),
    .B(_473_),
    .Y(_263_)
  );
  ANX1_CV _782_ (
    .A(_325_),
    .B(_471_),
    .Y(_474_)
  );
  ORX1_CV _783_ (
    .A(_325_),
    .B(_471_),
    .Y(_475_)
  );
  NDX1_CV _784_ (
    .A(_414_),
    .B(_475_),
    .Y(_476_)
  );
  NRX1_CV _785_ (
    .A(_474_),
    .B(_476_),
    .Y(_264_)
  );
  ANX1_CV _786_ (
    .A(_326_),
    .B(_474_),
    .Y(_477_)
  );
  ORX1_CV _787_ (
    .A(_326_),
    .B(_474_),
    .Y(_478_)
  );
  NDX1_CV _788_ (
    .A(_414_),
    .B(_478_),
    .Y(_479_)
  );
  NRX1_CV _789_ (
    .A(_477_),
    .B(_479_),
    .Y(_265_)
  );
  ANX1_CV _790_ (
    .A(_327_),
    .B(_477_),
    .Y(_480_)
  );
  ORX1_CV _791_ (
    .A(_327_),
    .B(_477_),
    .Y(_481_)
  );
  NDX1_CV _792_ (
    .A(_414_),
    .B(_481_),
    .Y(_482_)
  );
  NRX1_CV _793_ (
    .A(_480_),
    .B(_482_),
    .Y(_266_)
  );
  ANX1_CV _794_ (
    .A(_328_),
    .B(_480_),
    .Y(_483_)
  );
  ORX1_CV _795_ (
    .A(_328_),
    .B(_480_),
    .Y(_484_)
  );
  NDX1_CV _796_ (
    .A(_414_),
    .B(_484_),
    .Y(_485_)
  );
  NRX1_CV _797_ (
    .A(_483_),
    .B(_485_),
    .Y(_267_)
  );
  ANX1_CV _798_ (
    .A(_329_),
    .B(_483_),
    .Y(_486_)
  );
  ORX1_CV _799_ (
    .A(_329_),
    .B(_483_),
    .Y(_487_)
  );
  NDX1_CV _800_ (
    .A(_414_),
    .B(_487_),
    .Y(_488_)
  );
  NRX1_CV _801_ (
    .A(_486_),
    .B(_488_),
    .Y(_268_)
  );
  NDX1_CV _802_ (
    .A(_331_),
    .B(_486_),
    .Y(_489_)
  );
  ORX1_CV _803_ (
    .A(_331_),
    .B(_486_),
    .Y(_490_)
  );
  ANX1_CV _804_ (
    .A(_414_),
    .B(_490_),
    .Y(_491_)
  );
  ANX1_CV _805_ (
    .A(_489_),
    .B(_491_),
    .Y(_270_)
  );
  ENX1_CV _806_ (
    .A(_332_),
    .B(_489_),
    .Y(_492_)
  );
  ANX1_CV _807_ (
    .A(_414_),
    .B(_492_),
    .Y(_271_)
  );
  NRX1_CV _808_ (
    .A(_301_),
    .B(_345_),
    .Y(_287_)
  );
  NRX1_CV _809_ (
    .A(_299_),
    .B(_345_),
    .Y(_286_)
  );
  NRX1_CV _810_ (
    .A(_300_),
    .B(_345_),
    .Y(_285_)
  );
  ORX1_CV _811_ (
    .A(_559_),
    .B(_561_),
    .Y(_493_)
  );
  NRX1_CV _812_ (
    .A(_560_),
    .B(_493_),
    .Y(_494_)
  );
  ANX1_CV _813_ (
    .A(_288_),
    .B(_494_),
    .Y(_284_)
  );
  ANX1_CV _814_ (
    .A(_379_),
    .B(_406_),
    .Y(_495_)
  );
  IVX1_CV _815_ (
    .A(_495_),
    .Y(_496_)
  );
  NDX1_CV _816_ (
    .A(_343_),
    .B(_344_),
    .Y(_497_)
  );
  ANX1_CV _817_ (
    .A(_414_),
    .B(_497_),
    .Y(_498_)
  );
  ANX1_CV _818_ (
    .A(_495_),
    .B(_498_),
    .Y(_279_)
  );
  NDX1_CV _819_ (
    .A(_305_),
    .B(_376_),
    .Y(_499_)
  );
  NDX1_CV _820_ (
    .A(_387_),
    .B(_280_),
    .Y(_500_)
  );
  ANX1_CV _821_ (
    .A(_409_),
    .B(_500_),
    .Y(_501_)
  );
  ORX1_CV _822_ (
    .A(_305_),
    .B(_501_),
    .Y(_502_)
  );
  ANX1_CV _823_ (
    .A(_343_),
    .B(_412_),
    .Y(_503_)
  );
  NDX1_CV _824_ (
    .A(_499_),
    .B(_503_),
    .Y(_504_)
  );
  ANX1_CV _825_ (
    .A(_502_),
    .B(_504_),
    .Y(_505_)
  );
  NDX1_CV _826_ (
    .A(_334_),
    .B(_342_),
    .Y(_506_)
  );
  NRX1_CV _827_ (
    .A(_373_),
    .B(_506_),
    .Y(_507_)
  );
  ANX1_CV _828_ (
    .A(_369_),
    .B(_415_),
    .Y(_508_)
  );
  ANX1_CV _829_ (
    .A(_507_),
    .B(_508_),
    .Y(_509_)
  );
  NDX1_CV _830_ (
    .A(_368_),
    .B(_509_),
    .Y(_510_)
  );
  NDX1_CV _831_ (
    .A(_396_),
    .B(_510_),
    .Y(_511_)
  );
  ORX1_CV _832_ (
    .A(_304_),
    .B(_412_),
    .Y(_512_)
  );
  ANX1_CV _833_ (
    .A(_414_),
    .B(_512_),
    .Y(_513_)
  );
  NDX1_CV _834_ (
    .A(_511_),
    .B(_513_),
    .Y(_514_)
  );
  IVX1_CV _835_ (
    .A(_514_),
    .Y(_515_)
  );
  NDX1_CV _836_ (
    .A(_379_),
    .B(_515_),
    .Y(_516_)
  );
  NDX1_CV _837_ (
    .A(_555_),
    .B(_516_),
    .Y(_517_)
  );
  ANX1_CV _838_ (
    .A(_388_),
    .B(_505_),
    .Y(_518_)
  );
  NDX1_CV _839_ (
    .A(_517_),
    .B(_518_),
    .Y(_281_)
  );
  NDX1_CV _840_ (
    .A(_556_),
    .B(_514_),
    .Y(_519_)
  );
  ORX1_CV _841_ (
    .A(_387_),
    .B(_495_),
    .Y(_520_)
  );
  NDX1_CV _842_ (
    .A(_376_),
    .B(_503_),
    .Y(_521_)
  );
  ANX1_CV _843_ (
    .A(_409_),
    .B(_521_),
    .Y(_522_)
  );
  ANX1_CV _844_ (
    .A(_495_),
    .B(_522_),
    .Y(_523_)
  );
  ORX1_CV _845_ (
    .A(_306_),
    .B(_523_),
    .Y(_524_)
  );
  ANX1_CV _846_ (
    .A(_519_),
    .B(_524_),
    .Y(_525_)
  );
  NDX1_CV _847_ (
    .A(_520_),
    .B(_525_),
    .Y(_282_)
  );
  NDX1_CV _848_ (
    .A(_387_),
    .B(_496_),
    .Y(_526_)
  );
  ANX1_CV _849_ (
    .A(_522_),
    .B(_526_),
    .Y(_527_)
  );
  ORX1_CV _850_ (
    .A(_307_),
    .B(_527_),
    .Y(_528_)
  );
  NDX1_CV _851_ (
    .A(_557_),
    .B(_514_),
    .Y(_529_)
  );
  NDX1_CV _852_ (
    .A(_528_),
    .B(_529_),
    .Y(_283_)
  );
  ANX1_CV _853_ (
    .A(_303_),
    .B(_302_),
    .Y(_530_)
  );
  ORX1_CV _854_ (
    .A(_304_),
    .B(_530_),
    .Y(_531_)
  );
  ORX1_CV _855_ (
    .A(_562_),
    .B(_531_),
    .Y(_532_)
  );
  ORX1_CV _856_ (
    .A(_302_),
    .B(_527_),
    .Y(_533_)
  );
  ORX1_CV _857_ (
    .A(_305_),
    .B(_414_),
    .Y(_534_)
  );
  ANX1_CV _858_ (
    .A(_531_),
    .B(_534_),
    .Y(_535_)
  );
  ANX1_CV _859_ (
    .A(_511_),
    .B(_535_),
    .Y(_536_)
  );
  NDX1_CV _860_ (
    .A(_533_),
    .B(_536_),
    .Y(_537_)
  );
  ANX1_CV _861_ (
    .A(_532_),
    .B(_537_),
    .Y(_289_)
  );
  ORX1_CV _862_ (
    .A(_563_),
    .B(_531_),
    .Y(_538_)
  );
  ORX1_CV _863_ (
    .A(_303_),
    .B(_527_),
    .Y(_539_)
  );
  ORX1_CV _864_ (
    .A(_306_),
    .B(_414_),
    .Y(_540_)
  );
  ANX1_CV _865_ (
    .A(_531_),
    .B(_540_),
    .Y(_541_)
  );
  ANX1_CV _866_ (
    .A(_511_),
    .B(_541_),
    .Y(_542_)
  );
  NDX1_CV _867_ (
    .A(_539_),
    .B(_542_),
    .Y(_543_)
  );
  ANX1_CV _868_ (
    .A(_538_),
    .B(_543_),
    .Y(_290_)
  );
  ORX1_CV _869_ (
    .A(_564_),
    .B(_531_),
    .Y(_544_)
  );
  NDX1_CV _870_ (
    .A(_343_),
    .B(_510_),
    .Y(_545_)
  );
  NDX1_CV _871_ (
    .A(_396_),
    .B(_545_),
    .Y(_546_)
  );
  NDX1_CV _872_ (
    .A(_395_),
    .B(_503_),
    .Y(_547_)
  );
  ORX1_CV _873_ (
    .A(_307_),
    .B(_414_),
    .Y(_548_)
  );
  ANX1_CV _874_ (
    .A(_531_),
    .B(_548_),
    .Y(_549_)
  );
  ANX1_CV _875_ (
    .A(_520_),
    .B(_549_),
    .Y(_550_)
  );
  ANX1_CV _876_ (
    .A(_546_),
    .B(_550_),
    .Y(_551_)
  );
  NDX1_CV _877_ (
    .A(_547_),
    .B(_551_),
    .Y(_552_)
  );
  ANX1_CV _878_ (
    .A(_544_),
    .B(_552_),
    .Y(_291_)
  );
  NDX1_CV _879_ (
    .A(_564_),
    .B(_413_),
    .Y(_297_)
  );
  NDX1_CV _880_ (
    .A(_298_),
    .B(_284_),
    .Y(_553_)
  );
  NDX1_CV _881_ (
    .A(_413_),
    .B(_497_),
    .Y(_554_)
  );
  ANX1_CV _882_ (
    .A(_553_),
    .B(_554_),
    .Y(_296_)
  );
  DFSRQNX1_CV _883_ (
    .CK(clk),
    .D(_010_),
    .Q(readState[0]),
    .QN(_565_),
    .R(1'h0),
    .S(1'h0)
  );
  DFSRQNX1_CV _884_ (
    .CK(clk),
    .D(_011_),
    .Q(readState[1]),
    .QN(_566_),
    .R(1'h0),
    .S(1'h0)
  );
  DFSRQNX1_CV _885_ (
    .CK(clk),
    .D(_012_),
    .Q(readState[2]),
    .QN(_567_),
    .R(1'h0),
    .S(1'h0)
  );
  DFSRQNX1_CV _886_ (
    .CK(clk),
    .D(_013_),
    .Q(readState[3]),
    .QN(_568_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _887_ (
    .CK(clk),
    .D(_009_[0]),
    .Q(state[0]),
    .QN(_569_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _888_ (
    .CK(clk),
    .D(_009_[1]),
    .Q(state[1]),
    .QN(_570_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _889_ (
    .CK(clk),
    .D(_009_[2]),
    .Q(state[2]),
    .QN(_571_),
    .R(1'h0),
    .S(reset)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _890_ (
    .CK(clk),
    .D(_003_[0]),
    .Q(next_state[0]),
    .QN(_572_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _891_ (
    .CK(clk),
    .D(_003_[1]),
    .Q(next_state[1]),
    .QN(_573_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _892_ (
    .CK(clk),
    .D(_003_[2]),
    .Q(next_state[2]),
    .QN(_574_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _893_ (
    .CK(clk),
    .D(_000_[0]),
    .Q(counter[0]),
    .QN(_575_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _894_ (
    .CK(clk),
    .D(_000_[1]),
    .Q(counter[1]),
    .QN(_576_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _895_ (
    .CK(clk),
    .D(_000_[2]),
    .Q(counter[2]),
    .QN(_577_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _896_ (
    .CK(clk),
    .D(_000_[3]),
    .Q(counter[3]),
    .QN(_578_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _897_ (
    .CK(clk),
    .D(_000_[4]),
    .Q(counter[4]),
    .QN(_579_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _898_ (
    .CK(clk),
    .D(_000_[5]),
    .Q(counter[5]),
    .QN(_580_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _899_ (
    .CK(clk),
    .D(_000_[6]),
    .Q(counter[6]),
    .QN(_581_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _900_ (
    .CK(clk),
    .D(_000_[7]),
    .Q(counter[7]),
    .QN(_582_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _901_ (
    .CK(clk),
    .D(_000_[8]),
    .Q(counter[8]),
    .QN(_583_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _902_ (
    .CK(clk),
    .D(_000_[9]),
    .Q(counter[9]),
    .QN(_584_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _903_ (
    .CK(clk),
    .D(_000_[10]),
    .Q(counter[10]),
    .QN(_585_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _904_ (
    .CK(clk),
    .D(_000_[11]),
    .Q(counter[11]),
    .QN(_586_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _905_ (
    .CK(clk),
    .D(_000_[12]),
    .Q(counter[12]),
    .QN(_587_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _906_ (
    .CK(clk),
    .D(_000_[13]),
    .Q(counter[13]),
    .QN(_588_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _907_ (
    .CK(clk),
    .D(_000_[14]),
    .Q(counter[14]),
    .QN(_589_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _908_ (
    .CK(clk),
    .D(_000_[15]),
    .Q(counter[15]),
    .QN(_590_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _909_ (
    .CK(clk),
    .D(_000_[16]),
    .Q(counter[16]),
    .QN(_591_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _910_ (
    .CK(clk),
    .D(_000_[17]),
    .Q(counter[17]),
    .QN(_592_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _911_ (
    .CK(clk),
    .D(_000_[18]),
    .Q(counter[18]),
    .QN(_593_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _912_ (
    .CK(clk),
    .D(_000_[19]),
    .Q(counter[19]),
    .QN(_594_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _913_ (
    .CK(clk),
    .D(_000_[20]),
    .Q(counter[20]),
    .QN(_595_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _914_ (
    .CK(clk),
    .D(_000_[21]),
    .Q(counter[21]),
    .QN(_596_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _915_ (
    .CK(clk),
    .D(_000_[22]),
    .Q(counter[22]),
    .QN(_597_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _916_ (
    .CK(clk),
    .D(_000_[23]),
    .Q(counter[23]),
    .QN(_598_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _917_ (
    .CK(clk),
    .D(_000_[24]),
    .Q(counter[24]),
    .QN(_599_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _918_ (
    .CK(clk),
    .D(_000_[25]),
    .Q(counter[25]),
    .QN(_600_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _919_ (
    .CK(clk),
    .D(_000_[26]),
    .Q(counter[26]),
    .QN(_601_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _920_ (
    .CK(clk),
    .D(_000_[27]),
    .Q(counter[27]),
    .QN(_602_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _921_ (
    .CK(clk),
    .D(_000_[28]),
    .Q(counter[28]),
    .QN(_603_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _922_ (
    .CK(clk),
    .D(_000_[29]),
    .Q(counter[29]),
    .QN(_604_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _923_ (
    .CK(clk),
    .D(_000_[30]),
    .Q(counter[30]),
    .QN(_605_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:142" *)
  DFSRQNX1_CV _924_ (
    .CK(clk),
    .D(_000_[31]),
    .Q(counter[31]),
    .QN(_606_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelSensorFsm.v:67" *)
  \$_DLATCH_P_  _925_ (
    .D(_005_),
    .E(_014_),
    .Q(read1)
  );
  (* src = "pixelSensorFsm.v:67" *)
  \$_DLATCH_P_  _926_ (
    .D(_006_),
    .E(_014_),
    .Q(read2)
  );
  (* src = "pixelSensorFsm.v:67" *)
  \$_DLATCH_P_  _927_ (
    .D(_007_),
    .E(_014_),
    .Q(read3)
  );
  (* src = "pixelSensorFsm.v:67" *)
  \$_DLATCH_P_  _928_ (
    .D(_008_),
    .E(_015_),
    .Q(readStateOn)
  );
  (* src = "pixelSensorFsm.v:67" *)
  \$_DLATCH_P_  _929_ (
    .D(_004_),
    .E(_014_),
    .Q(read0)
  );
  (* src = "pixelSensorFsm.v:67" *)
  \$_DLATCH_P_  _930_ (
    .D(_001_),
    .E(_015_),
    .Q(erase)
  );
  (* src = "pixelSensorFsm.v:67" *)
  \$_DLATCH_P_  _931_ (
    .D(_002_),
    .E(_015_),
    .Q(expose)
  );
  assign convert = 1'h0;
  assign _079_ = _565_;
  assign _074_ = _566_;
  assign _241_ = _567_;
  assign _083_ = _568_;
  assign _209_ = _569_;
  assign _210_ = _570_;
  assign _055_ = _571_;
  assign _173_ = _572_;
  assign _191_ = _573_;
  assign _200_ = _574_;
  assign _308_ = counter[0];
  assign _319_ = counter[1];
  assign _330_ = counter[2];
  assign _333_ = counter[3];
  assign _334_ = counter[4];
  assign _335_ = counter[5];
  assign _337_ = counter[7];
  assign _336_ = counter[6];
  assign _339_ = counter[9];
  assign _338_ = counter[8];
  assign _310_ = counter[11];
  assign _309_ = counter[10];
  assign _312_ = counter[13];
  assign _311_ = counter[12];
  assign _314_ = counter[15];
  assign _313_ = counter[14];
  assign _316_ = counter[17];
  assign _315_ = counter[16];
  assign _318_ = counter[19];
  assign _317_ = counter[18];
  assign _321_ = counter[21];
  assign _320_ = counter[20];
  assign _323_ = counter[23];
  assign _322_ = counter[22];
  assign _325_ = counter[25];
  assign _324_ = counter[24];
  assign _327_ = counter[27];
  assign _326_ = counter[26];
  assign _329_ = counter[29];
  assign _328_ = counter[28];
  assign _332_ = counter[31];
  assign _331_ = counter[30];
  assign _564_ = state[2];
  assign _563_ = state[1];
  assign _562_ = state[0];
  assign _304_ = _571_;
  assign _008_ = _288_;
  assign _300_ = _567_;
  assign _012_ = _294_;
  assign _559_ = readState[1];
  assign _299_ = _566_;
  assign _011_ = _293_;
  assign _002_ = _280_;
  assign _558_ = readState[0];
  assign _298_ = _565_;
  assign _010_ = _292_;
  assign _561_ = readState[3];
  assign _301_ = _568_;
  assign _013_ = _295_;
  assign _000_[0] = _247_;
  assign _000_[1] = _258_;
  assign _000_[2] = _269_;
  assign _000_[3] = _272_;
  assign _000_[4] = _273_;
  assign _000_[5] = _274_;
  assign _000_[6] = _275_;
  assign _000_[7] = _276_;
  assign _000_[8] = _277_;
  assign _000_[9] = _278_;
  assign _000_[10] = _248_;
  assign _000_[11] = _249_;
  assign _000_[12] = _250_;
  assign _000_[13] = _251_;
  assign _000_[14] = _252_;
  assign _000_[15] = _253_;
  assign _000_[16] = _254_;
  assign _000_[17] = _255_;
  assign _000_[18] = _256_;
  assign _000_[19] = _257_;
  assign _000_[20] = _259_;
  assign _000_[21] = _260_;
  assign _000_[22] = _261_;
  assign _000_[23] = _262_;
  assign _000_[24] = _263_;
  assign _000_[25] = _264_;
  assign _000_[26] = _265_;
  assign _000_[27] = _266_;
  assign _000_[28] = _267_;
  assign _000_[29] = _268_;
  assign _000_[30] = _270_;
  assign _000_[31] = _271_;
  assign _007_ = _287_;
  assign _006_ = _286_;
  assign _005_ = _285_;
  assign _560_ = readState[2];
  assign _004_ = _284_;
  assign _001_ = _279_;
  assign _555_ = next_state[0];
  assign _305_ = _572_;
  assign _003_[0] = _281_;
  assign _556_ = next_state[1];
  assign _306_ = _573_;
  assign _003_[1] = _282_;
  assign _557_ = next_state[2];
  assign _307_ = _574_;
  assign _003_[2] = _283_;
  assign _303_ = _570_;
  assign _302_ = _569_;
  assign _009_[0] = _289_;
  assign _009_[1] = _290_;
  assign _009_[2] = _291_;
  assign _015_ = _297_;
  assign _014_ = _296_;
endmodule
